name: VaultScan Secrets Detection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vaultscan:
    name: Run VaultScan on Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run VaultScan via GitHub Action
        uses: vaultscanhq/vaultscan-action@v1.2